import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="relative">
          {/* Imagen de fondo con borde inferior diagonal */}
          <div
            className="hidden md:block absolute inset-0 bg-cover bg-center bg-no-repeat z-[-1] h-[750px] clip-path-diagonal"
            style={{
              backgroundImage: "url('/equipo.png')",
              backgroundBlendMode: "overlay",
              backgroundColor: "rgba(0, 15, 74, 0.5)" // Color azul con opacidad
            }}
          >
            {/* Gradiente de azul intenso a más suave */}
            <div
              className="absolute inset-0 bg-gradient-to-r from-blue-950 to-blue-800 opacity-90"
              style={{ backgroundBlendMode: "overlay" }}
            />
          </div>

          {/* Resto del contenido */}
          <Navbar />
          <div>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}